// Command Code mod: a status line under the input box
// Segments: model / effort / context bar / cache hit / session cost / output speed / sub-agents /
//           session name / git branch and changes / current directory name
//
// Deploy: cp index.ts ~/.commandcode/mods/statusline.ts
//         (or install: cmd mods add holtwood/cmdc-statusline -g; dry run without installing: cmd --mod ./index.ts)
// Requires: cmdc >= MIN_HOST_VERSION (currently 1.10.0). Old hosts are not supported: a stale version detected on load
//         disables the mod — one upgrade notice in the message area only, no flag / command / hook / footer. An unreadable version counts as usable (never guess).
// Background: cmdc has no Claude Code style statusLine external-command hook, and the mod's cmd.ui.setStatus is the only
//           interface that can render a persistent status segment under the input box (see mod-builder reference/ui.md); this mod implements it that way.
// The two built-in tables (context windows / prices) are generated by scripts/gen-model-tables.py from the product model list; do not hand-edit.
// Cost is the session total = the history summed from the transcript on resume + the part produced by this process (a restart does not reset it).
// Besides cost, the same resume scan seeds model/effort/context/cache hit of the last request; on a freshly started cmdc with
// no request yet, model/effort are first painted from ~/.commandcode/config.json — otherwise the footer would only fill in
// at the first model_request_end, leaving just git and the directory name in between.
//
// Config (precedence: built-in default < preset < user scope < project scope < command line):
//   ~/.commandcode/statusline.json          user scope
//   <project>/.commandcode/statusline.json  project scope (overrides user scope)
//   --mod-option statusline.<key>=<value>   command line (counts as an explicit override only when the value differs
//                                           from the built-in default — cmdc erases --mod-option values from the argv
//                                           visible to the mod, so 'the default was passed explicitly' cannot be told apart)
//   Available keys: model/effort/context/bar/bar-width/percent/cache/cost/speed/sub/name/git/cwd/
//          preset/raw-model/ascii/refresh/lang (lang only affects the report and the modal copy)
//   preset: plus (model+effort+context+cache+cost+sub, the default) / full (everything) /
//           minimal (model+effort+context+bar+percent+git) / usage (context+cache+cost+sub-agents).
//           It only decides which segments are on; writing a single key overrides it. Render switches (ascii/raw-model) are unrelated to it.
//
// Why flag names carry a prefix but config keys do not: the host keeps mod flag values in a process-wide table indexed by
// name (measured: addFlag writes defaults first come first served, getFlag always reads from that table, and the type of a
// --mod-option is decided by the first declarer) — two mods declaring the same flag silently cross values and the other side
// cannot even read its own default. Config files do not have this problem: the file name statusline.json is itself the namespace.
// So only flag names sent to the host carry the statusline. prefix; keys (JSON, report table, selector) stay short; flagName() is the only derivation point.
//
// Self-service troubleshooting and config (no need to dig through the README):
//   /statusline          prints the full 'key / default / effective / source' table and warns separately about unknown
//                        (typo) and wrongly typed keys from the JSON; file sources are listed as well
//   /statusline config   edits interactively via cmd.ui.select/input/confirm; writes and repaints right away, no /reload
//
// Narrow terminals: degrade by priority (drop cwd → speed → effort → sub-agents → cache → session name → cost → changes first,
//         context degrades step by step from bar+token+percent, branch goes last, the model is never dropped), and listen to resize to repaint immediately.

import {createReadStream, existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync} from 'node:fs';
import {homedir} from 'node:os';
import {dirname, join} from 'node:path';
import {createInterface} from 'node:readline';
// ModApi's type is not in any published package (@commandcode/harness is unpublished) — use the repo-local declaration,
// it is only for tsc --noEmit; at runtime import type is erased entirely, never resolved, and does not affect single-file deploy.
import type {ModApi} from './mod-api.js';

// ── Types ───────────────────────────────────────────────────────────────────────────
type Usage = {
	readonly inputTokens?: number;
	readonly outputTokens?: number;
	readonly cacheReadTokens?: number;
	readonly cacheWriteTokens?: number;
};

type ModelEvent = {
	readonly model?: string;
	readonly effort?: string;
	readonly usage?: Usage;
};

type ConfigChangedEvent = {
	readonly setting?: string;
	readonly value?: unknown;
};

type SessionEvent = {
	readonly source?: string;
	readonly sessionId?: string;
};

type SubagentStopEvent = {
	readonly subagentType?: string;
	readonly tokensUsed?: number;
};

type GitInfo = {
	isRepo: boolean;
	branch?: string;
	ahead: number;
	behind: number;
	staged: number;
	modified: number;
	untracked: number;
};

type Snapshot = GitInfo & {
	model?: string;
	effort?: string;
	contextTokens?: number;
	cacheHit?: number;
	title?: string;
	costUsd: number;
	speed?: number;
	subTokens: number;
};

type Segments = {
	readonly model: boolean;
	readonly effort: boolean;
	readonly context: boolean;
	readonly bar: boolean;
	readonly percent: boolean;
	readonly cache: boolean;
	readonly cost: boolean;
	readonly speed: boolean;
	readonly sub: boolean;
	readonly name: boolean;
	readonly git: boolean;
	readonly cwd: boolean;
};

// All mutable state of a session lives in one object: the mod is installed once per process, but the host swaps sessions
// in the same process (onSessionEnd's reason can be 'replaced' — navigateTree and resuming another session both go that way).
// When the id changes, rebuild it wholesale: name, cost and seed flags must not leak into the next session.
// Every new field must go into freshSession() — the type forces it, so 'added a field, forgot to reset it' cannot happen.
type SessionState = {
	id?: string;
	seeded: boolean;
	seededCost: number;
	sessionCost: number;
	/** the transcript has usage/model lines but no tail anchor matched → the format may have changed; the report names it */
	seedDrifted: boolean;
	snapshot: Snapshot;
};

const freshSession = (id?: string): SessionState => ({
	id,
	seeded: false,
	seededCost: 0,
	sessionCost: 0,
	seedDrifted: false,
	snapshot: {
		isRepo: false,
		ahead: 0,
		behind: 0,
		staged: 0,
		modified: 0,
		untracked: 0,
		costUsd: 0,
		subTokens: 0,
	},
});

type ComposeOptions = {
	readonly color: boolean;
	readonly rawModel: boolean;
	readonly mode: ColorMode;
	readonly barWidth: number;
	readonly maxWidth?: number;
	readonly cwd?: string;
};

type ColorMode = 'truecolor' | 'ansi256' | 'ascii';

type Config = Record<string, unknown>;

// ── Constants ───────────────────────────────────────────────────────────────────────
const SEP = ' │ ';
const BRAND = '⟡';
const GIT_TTL_MS = 5000;
const GIT_TIMEOUT_MS = 10_000;
const TITLE_COLUMNS = 24;
const COST_WARN_USD = 1;
const COST_ALERT_USD = 10;

// Adaptive backoff for slow repos: the allowed interval = max(GIT_TTL_MS, GIT_BACKOFF × the last measured duration),
// i.e. 'git takes at most 20% of wall-clock time'. A normal repo always stays under the 5 second floor, exactly as before.
const GIT_BACKOFF = 5;

// Loop bound for narrow-terminal degradation, see composeLine: never reached in practice, a backstop for logic bugs
const DROP_STEPS_MAX = 64;

export function gitGapMs(durationMs: number): number {
	return Math.max(GIT_TTL_MS, GIT_BACKOFF * Math.max(0, durationMs));
}

const ANSI_PATTERN = /\u001b\[[0-9;]*m/g;

// Narrow-terminal drop order: the higher the number, the earlier it is dropped; 0 = never dropped.
// Note these keys are not flag keys: the git segment is split into gitBranch / gitChanges entries at render time,
// each with its own rank here. The entry key type is taken from this table (DropKey), so a wrong name in push()
// is a compile error rather than silently landing on a middle priority as before.
const DROP_ORDER = {
	cwd: 11,
	speed: 10,
	effort: 9,
	sub: 8,
	cache: 7,
	name: 6,
	cost: 5,
	gitChanges: 4,
	context: 3,
	gitBranch: 2,
	model: 0,
} as const;

type DropKey = keyof typeof DROP_ORDER;

const ANSI = {
	reset: '\u001b[0m',
	bold: '\u001b[1m',
	dim: '\u001b[2m',
	red: '\u001b[31m',
	green: '\u001b[32m',
	yellow: '\u001b[33m',
	cyan: '\u001b[36m',
	magenta: '\u001b[35m',
	gray: '\u001b[90m',
};

// ── Pure functions: formatting, width, colour, git parsing, compose ─────────────────
// These two tables live in the generated section at the end of the file (machine-written) — use them only through these two accessors, never index them elsewhere
export function contextWindowFor(model?: string): number | undefined {
	return model ? MODEL_CONTEXT_WINDOWS[model] : undefined;
}

export function modelPriceFor(model?: string): ModelPrice | undefined {
	return model ? MODEL_PRICES[model] : undefined;
}

export function shortModel(model: string): string {
	const index = model.lastIndexOf('/');
	return index === -1 ? model : model.slice(index + 1);
}

// cmd.cwd is a backslash absolute path on Windows (measured D:\...), so both separators must be split
export function cwdBasename(cwd: string): string | undefined {
	const parts = cwd.split(/[/\\]/).filter(Boolean);
	return parts.length > 0 ? parts[parts.length - 1] : undefined;
}

export function formatTokens(tokens: number): string {
	if (tokens < 1000) return String(tokens);
	if (tokens < 10000) return `${(tokens / 1000).toFixed(1)}k`;
	return `${Math.round(tokens / 1000)}k`;
}

export function formatWindow(tokens: number): string {
	if (tokens >= 1_000_000) {
		const millions = tokens / 1_000_000;
		return `${Number.isInteger(millions) ? millions : millions.toFixed(2)}M`;
	}
	return `${Math.round(tokens / 1000)}k`;
}

export function formatPercent(tokens: number, window: number): string {
	const percent = (tokens / window) * 100;
	if (percent <= 0) return '0%';
	if (percent >= 10) return `${Math.round(percent)}%`;
	return `${percent.toFixed(1)}%`;
}

export function formatRate(percent: number): string {
	if (percent >= 99.95) return '100%';
	if (percent >= 10) return `${Math.floor(percent)}%`;
	return `${percent.toFixed(1)}%`;
}

export function formatCost(usd: number): string {
	if (usd <= 0) return '$0';
	const digits = usd < 0.0001 ? 5 : usd < 0.01 ? 4 : usd < 1 ? 3 : 2;
	const text = usd.toFixed(digits).replace(/0+$/, '').replace(/\.$/, '');
	return `$${text}`;
}

export function estimateCost(usage: Usage, model?: string): number {
	const price = modelPriceFor(model);
	if (!price) return 0;
	const cacheRead = usage.cacheReadTokens ?? 0;
	const cacheWrite = usage.cacheWriteTokens ?? 0;
	const uncached = Math.max(0, (usage.inputTokens ?? 0) - cacheRead - cacheWrite);
	return (
		(uncached * price.in +
			cacheRead * price.cacheRead +
			cacheWrite * price.cacheWrite +
			(usage.outputTokens ?? 0) * price.out) /
		1_000_000
	);
}

export function cacheHitRate(usage: Usage): number | undefined {
	const input = usage.inputTokens ?? 0;
	if (input <= 0) return undefined;
	return ((usage.cacheReadTokens ?? 0) / input) * 100;
}

export function rgbForPosition(t: number): [number, number, number] {
	const mix = (from: number[], to: number[], k: number): [number, number, number] => [
		Math.round(from[0] + (to[0] - from[0]) * k),
		Math.round(from[1] + (to[1] - from[1]) * k),
		Math.round(from[2] + (to[2] - from[2]) * k),
	];
	const position = Math.max(0, Math.min(1, t));
	return position < 0.5
		? mix([0, 200, 0], [200, 200, 0], position / 0.5)
		: mix([200, 200, 0], [200, 0, 0], (position - 0.5) / 0.5);
}

function sgrColor([r, g, b]: [number, number, number], mode: ColorMode): string {
	if (mode === 'truecolor') return `\u001b[38;2;${r};${g};${b}m`;
	const toCube = (value: number) => Math.round((value / 255) * 5);
	return `\u001b[38;5;${16 + 36 * toCube(r) + 6 * toCube(g) + toCube(b)}m`;
}

export function renderBar(
	percent: number,
	width: number,
	mode: ColorMode,
	color: boolean,
): string {
	const ratio = Math.max(0, Math.min(100, percent)) / 100;
	const filled = Math.max(percent > 0 ? 1 : 0, Math.round(ratio * width));
	const cells: string[] = [];
	for (let index = 0; index < width; index += 1) {
		const isFilled = index < filled;
		const glyph = mode === 'ascii' ? (isFilled ? '#' : '-') : isFilled ? '█' : '░';
		if (!color) {
			cells.push(glyph);
			continue;
		}
		if (!isFilled) {
			cells.push(`${ANSI.dim}${glyph}${ANSI.reset}`);
			continue;
		}
		const position = width > 1 ? index / (width - 1) : 0;
		cells.push(`${sgrColor(rgbForPosition(position), mode)}${glyph}${ANSI.reset}`);
	}
	return cells.join('');
}

// Terminal display width: ANSI does not count; CJK / fullwidth / common emoji take 2 columns (counting code points would make a CJK title half as wide as it is)
const WIDE_CHAR =
	/[\u{1100}-\u{115F}\u{2E80}-\u{303E}\u{3041}-\u{33FF}\u{3400}-\u{4DBF}\u{4E00}-\u{9FFF}\u{A000}-\u{A4CF}\u{AC00}-\u{D7A3}\u{F900}-\u{FAFF}\u{FE30}-\u{FE6F}\u{FF00}-\u{FF60}\u{FFE0}-\u{FFE6}\u{1F300}-\u{1F64F}\u{1F900}-\u{1F9FF}\u{20000}-\u{3FFFD}]/u;

export function visibleLength(text: string): number {
	let width = 0;
	for (const char of text.replace(ANSI_PATTERN, '')) {
		width += WIDE_CHAR.test(char) ? 2 : 1;
	}
	return width;
}

export function truncateToWidth(text: string, max: number): string {
	if (visibleLength(text) <= max) return text;
	let width = 0;
	let out = '';
	for (const char of text) {
		const next = width + (WIDE_CHAR.test(char) ? 2 : 1);
		if (next > max - 1) break;
		width = next;
		out += char;
	}
	return `${out}…`;
}

export function parseGitStatus(porcelain: string, isRepo = true): GitInfo {
	const info = {
		isRepo,
		branch: undefined as string | undefined,
		ahead: 0,
		behind: 0,
		staged: 0,
		modified: 0,
		untracked: 0,
	};
	for (const line of porcelain.split('\n')) {
		if (!line) continue;
		if (line.startsWith('## ')) {
			const header = line.slice(3);
			if (header.startsWith('HEAD (no branch)')) {
				info.branch = 'detached';
			} else {
				info.branch = header.split('...')[0].split(' ')[0];
				const ahead = /ahead (\d+)/.exec(header);
				const behind = /behind (\d+)/.exec(header);
				if (ahead) info.ahead = Number(ahead[1]);
				if (behind) info.behind = Number(behind[1]);
			}
			continue;
		}
		const index = line[0];
		const worktree = line[1];
		if (index === '?' && worktree === '?') {
			info.untracked += 1;
			continue;
		}
		if (index !== ' ' && index !== '?') info.staged += 1;
		if (worktree !== ' ' && worktree !== '?') info.modified += 1;
	}
	return info;
}

export function composeLine(
	snapshot: Snapshot,
	segments: Segments,
	options: ComposeOptions,
): string {
	const paint = (code: string, text: string) =>
		options.color ? `${code}${text}${ANSI.reset}` : text;
	const entries: {key: DropKey; priority: number; variants: string[]}[] = [];
	const push = (key: DropKey, variants: string[]): void => {
		const filled = variants.filter(Boolean);
		if (filled.length > 0) {
			entries.push({key, priority: DROP_ORDER[key], variants: filled});
		}
	};

	if (segments.model && snapshot.model) {
		const name = options.rawModel ? snapshot.model : shortModel(snapshot.model);
		push('model', [paint(ANSI.bold + ANSI.cyan, name)]);
	}
	if (segments.effort && snapshot.effort) {
		push('effort', [paint(ANSI.dim, snapshot.effort)]);
	}
	if (segments.context && snapshot.contextTokens) {
		const window = contextWindowFor(snapshot.model);
		const percent = window ? (snapshot.contextTokens / window) * 100 : undefined;
		const withBar = segments.bar && percent !== undefined && options.barWidth > 0;
		const tokens = paint(
			ANSI.gray,
			`${withBar ? '' : 'ctx '}${formatTokens(snapshot.contextTokens)}`,
		);
		const bar = withBar
			? renderBar(percent as number, options.barWidth, options.mode, options.color)
			: '';
		const percentText =
			segments.percent && percent !== undefined
				? paint(percent >= 90 ? ANSI.red : percent >= 80 ? ANSI.yellow : ANSI.gray, `(${formatPercent(snapshot.contextTokens, window as number)})`)
				: '';
		push('context', [
			[bar, tokens, percentText].filter(Boolean).join(' '),
			[tokens, percentText].filter(Boolean).join(' '),
			paint(ANSI.gray, `ctx ${formatTokens(snapshot.contextTokens)}`),
		]);
	}
	if (segments.cache && snapshot.cacheHit !== undefined) {
		const code =
			snapshot.cacheHit >= 90 ? ANSI.green : snapshot.cacheHit >= 50 ? ANSI.gray : ANSI.yellow;
		push('cache', [paint(code, `cache ${formatRate(snapshot.cacheHit)}`)]);
	}
	if (segments.cost && snapshot.costUsd > 0) {
		const code =
			snapshot.costUsd >= COST_ALERT_USD
				? ANSI.red
				: snapshot.costUsd >= COST_WARN_USD
					? ANSI.yellow
					: ANSI.gray;
		push('cost', [paint(code, formatCost(snapshot.costUsd))]);
	}
	if (segments.speed && snapshot.speed && Math.round(snapshot.speed) > 0) {
		push('speed', [paint(ANSI.gray, `${Math.round(snapshot.speed)} tok/s`)]);
	}
	if (segments.sub && snapshot.subTokens > 0) {
		push('sub', [paint(ANSI.gray, `sub ${formatTokens(snapshot.subTokens)}`)]);
	}
	if (segments.name && snapshot.title) {
		push('name', [paint(ANSI.bold, truncateToWidth(snapshot.title, TITLE_COLUMNS))]);
	}
	if (segments.git && snapshot.isRepo && snapshot.branch) {
		let branch = paint(ANSI.magenta, snapshot.branch);
		if (snapshot.ahead > 0 || snapshot.behind > 0) {
			const delta = [
				snapshot.ahead > 0 ? `↑${snapshot.ahead}` : '',
				snapshot.behind > 0 ? `↓${snapshot.behind}` : '',
			]
				.filter(Boolean)
				.join('');
			branch += paint(ANSI.dim, ` ${delta}`);
		}
		push('gitBranch', [branch, paint(ANSI.magenta, snapshot.branch)]);
		const changes = [
			snapshot.staged > 0 ? paint(ANSI.green, `+${snapshot.staged}`) : '',
			snapshot.modified > 0 ? paint(ANSI.yellow, `~${snapshot.modified}`) : '',
			snapshot.untracked > 0 ? paint(ANSI.gray, `?${snapshot.untracked}`) : '',
		]
			.filter(Boolean)
			.join(' ');
		push('gitChanges', [changes || paint(ANSI.dim, 'clean'), '']);
	}
	if (segments.cwd && options.cwd) {
		push('cwd', [paint(ANSI.gray, options.cwd)]);
	}

	const variantIndex = new Map<string, number>(entries.map(entry => [entry.key, 0]));
	const joined = (): string =>
		entries
			.map(entry => entry.variants[variantIndex.get(entry.key) ?? 0])
			.filter(Boolean)
			.join(paint(ANSI.dim, SEP));

	const maxWidth = options.maxWidth ?? 0;
	if (maxWidth > 0) {
		// Each round either degrades one entry's variant by one step or drops it entirely, so the number of rounds is bounded anyway;
		// DROP_STEPS_MAX is a backstop for bugs in the 'measure width / drop entries' logic itself (do not spin forever).
		let guard = 0;
		while (visibleLength(joined()) > maxWidth && guard < DROP_STEPS_MAX) {
			guard += 1;
			const droppable = entries
				.filter(entry => entry.priority > 0)
				.sort((a, b) => b.priority - a.priority);
			const target = droppable[0];
			if (!target) break;
			const index = variantIndex.get(target.key) ?? 0;
			if (index < target.variants.length - 1) {
				variantIndex.set(target.key, index + 1);
			} else {
				entries.splice(entries.indexOf(target), 1);
			}
		}
	}

	return joined();
}

// ── flag registry (single source of truth for key names) ────────────────────────────
type FlagSpec = {
	readonly name: string;
	readonly type: 'boolean' | 'string';
	readonly default: boolean | string;
	readonly description: string;
	readonly descriptionEn: string;
	readonly segment?: boolean;
	/** numeric keys: the value must parse to a non-negative number (strings and numbers both accepted) */
	readonly numeric?: boolean;
	readonly max?: number;
};

// Single source of truth for keys: addFlag, the /statusline table and the interactive selector all read here, no more separate copies
const FLAG_SPECS: readonly FlagSpec[] = [
	{name: 'model', type: 'boolean', default: true, description: 'show the active model', descriptionEn: 'show the active model', segment: true},
	{name: 'effort', type: 'boolean', default: true, description: 'show the thinking effort', descriptionEn: 'show the thinking effort', segment: true},
	{name: 'context', type: 'boolean', default: true, description: 'context tokens of the last request', descriptionEn: 'context tokens of the last request', segment: true},
	{name: 'bar', type: 'boolean', default: true, description: 'gradient bar of context window share (needs a known window)', descriptionEn: 'gradient bar of context window share (needs a known window)', segment: true},
	{name: 'percent', type: 'boolean', default: true, description: 'context share of the model window', descriptionEn: 'context share of the model window', segment: true},
	{name: 'cache', type: 'boolean', default: true, description: 'cache hit rate of the last request', descriptionEn: 'cache hit rate of the last request', segment: true},
	{name: 'cost', type: 'boolean', default: true, description: 'session cost (estimated via the built-in price table)', descriptionEn: 'session cost (estimated via the built-in price table)', segment: true},
	{name: 'speed', type: 'boolean', default: true, description: 'output speed of the last request (tok/s)', descriptionEn: 'output speed of the last request (tok/s)', segment: true},
	{name: 'sub', type: 'boolean', default: true, description: 'tokens burned by sub-agents', descriptionEn: 'tokens burned by sub-agents', segment: true},
	{name: 'name', type: 'boolean', default: true, description: 'show the session name', descriptionEn: 'show the session name', segment: true},
	{name: 'git', type: 'boolean', default: true, description: 'git branch + changes', descriptionEn: 'git branch + changes', segment: true},
	{name: 'cwd', type: 'boolean', default: true, description: 'current directory basename', descriptionEn: 'current directory basename', segment: true},
	{name: 'preset', type: 'string', default: 'plus', description: 'segment preset: plus / full / minimal / usage (a single key overrides it)', descriptionEn: 'segment preset: plus / full / minimal / usage (a single key overrides it)'},
	{name: 'bar-width', type: 'string', default: '12', description: 'bar width in cells', descriptionEn: 'bar width in cells', numeric: true, max: 40},
	{name: 'raw-model', type: 'boolean', default: false, description: 'full model id (keep the vendor prefix)', descriptionEn: 'full model id (keep the vendor prefix)'},
	{name: 'ascii', type: 'boolean', default: false, description: 'plain ASCII rendering (no Unicode blocks, no colour)', descriptionEn: 'plain ASCII rendering (no Unicode blocks, no colour)'},
	{name: 'refresh', type: 'string', default: '10', description: 'seconds between git re-reads (0 disables polling)', descriptionEn: 'seconds between git re-reads (0 disables polling)', numeric: true, max: 3600},
	{name: 'lang', type: 'string', default: 'en', description: 'ui language (en)', descriptionEn: 'ui language (en)'},
];

const FLAG_BY_NAME = new Map(FLAG_SPECS.map(spec => [spec.name, spec]));

// 'key' and 'flag name' are two names for the same thing: the key is the short name in statusline.json (also the name in the
// report table and the selector), while the flag name is the one handed to the host and must be prefixed — the host's flag value
// table is process-wide and name-indexed, so no prefix means a collision with another mod (see the file header). Derivation lives here only: change the prefix and everything changes.
export function flagName(key: string): string {
	return `statusline.${key}`;
}

// ── preset and value validation / normalisation ─────────────────────────────────────
// A preset only decides segment switches; keys it does not list count as 'off' (otherwise minimal would not be minimal)
const PRESETS: Record<string, Record<string, boolean>> = {
	full: {
		model: true,
		effort: true,
		context: true,
		bar: true,
		percent: true,
		cache: true,
		cost: true,
		speed: true,
		sub: true,
		name: true,
		git: true,
		cwd: true,
	},
	minimal: {model: true, effort: true, context: true, bar: true, percent: true, git: true},
	usage: {context: true, bar: true, percent: true, cache: true, cost: true, sub: true},
	plus: {model: true, effort: true, context: true, bar: true, percent: true, cache: true, cost: true, sub: true},
};

const PRESET_NAMES = ['plus', 'full', 'minimal', 'usage'];

function isPresetName(value: unknown): boolean {
	return typeof value === 'string' && Object.prototype.hasOwnProperty.call(PRESETS, value);
}

// The preset's value for a key; undefined when the key is not a segment key (ascii/raw-model/refresh...) or the preset name is unknown
function presetValue(preset: string, key: string): boolean | undefined {
	if (!FLAG_BY_NAME.get(key)?.segment || !isPresetName(preset)) return undefined;
	return PRESETS[preset][key] ?? false;
}

// Whether this value is usable in the config file: boolean keys must be booleans; numeric keys accept a number or a numeric string but must parse to a non-negative number;
// all other string keys (currently only preset) accept strings only — otherwise {"preset": 123} would pass as usable,
// the report would copy 123 as the effective value while presetName() accepts strings only and actually runs full: the table would lie again.
function acceptsValue(spec: FlagSpec, value: unknown): boolean {
	if (spec.type === 'boolean') return typeof value === 'boolean';
	if (spec.numeric) {
		if (typeof value !== 'string' && typeof value !== 'number') return false;
		const parsed = Number(value);
		return Number.isFinite(parsed) && parsed >= 0;
	}
	return typeof value === 'string';
}

type Lang = 'en';

// Normalisation of the lang key: en / en-US are recognised; anything else returns undefined (the report names it, English is used)
function langOf(value: unknown): Lang | undefined {
	if (typeof value !== 'string') return undefined;
	const head = value.trim().toLowerCase();
	if (head === 'en' || head.startsWith('en-') || head.startsWith('en_')) return 'en';
	return undefined;
}

function describeExpectation(spec: FlagSpec, lang: Lang = 'en'): string {
	if (spec.numeric) return 'non-negative number';
	return spec.type === 'boolean' ? 'true / false' : 'string';
}

// Normalisation of numeric keys: if it parses to a non-negative number, take the integer clamped to max; otherwise fall back to the default.
// flagNumber() and the report table both go through here — otherwise with bar-width: 100 the table would report 100 while the footer uses 40.
function clampedNumber(spec: FlagSpec, value: unknown): number {
	const parsed = Number(value);
	if (!Number.isFinite(parsed) || parsed < 0) return Number(spec.default);
	return Math.min(spec.max ?? Number.MAX_SAFE_INTEGER, Math.floor(parsed));
}

// preset / lang names are case-insensitive (presetName() and langOf() normalise the same way): without this,
// the report table would print 'Minimal' / 'EN' verbatim — disagreeing with the value actually in effect
function canonical(spec: FlagSpec, value: unknown): unknown {
	if (typeof value !== 'string') return value;
	if (spec.name === 'preset') return value.toLowerCase();
	// en-US → en; unrecognised values are kept as-is, reported verbatim by the report, and English is used in practice
	if (spec.name === 'lang') return langOf(value) ?? value;
	return value;
}

// ── config files (path, read, write) ────────────────────────────────────────────────
function userConfigPath(): string {
	return join(homedir(), '.commandcode', 'statusline.json');
}

function projectConfigPath(cwd: string): string {
	return join(cwd, '.commandcode', 'statusline.json');
}

type ConfigLoad = {
	readonly config: Config;
	readonly sources: readonly string[];
	/** which file last set each key (the report needs this to print the source) */
	readonly origin: Record<string, string>;
	/** file exists but cannot be read (invalid JSON / top level not an object): silently skipping would make 'I changed it and nothing happened' inexplicable */
	readonly broken: readonly string[];
};

// Notepad on Windows writes UTF-8 with a BOM and JSON.parse throws on it — such files used to be ignored entirely,
// leaving the user with 'the config had no effect' although the file content was perfectly fine. Strip it when reading.
function stripBom(text: string): string {
	return text.startsWith('\uFEFF') ? text.slice(1) : text;
}

export function loadConfig(cwd: string): ConfigLoad {
	// No prototype: otherwise a '__proto__' key in the file would change config's prototype, config[name] would read an inherited value,
	// while origin has no entry for it — making the report pass a file value off as a built-in default. Same for origin.
	const config: Config = Object.create(null) as Config;
	const origin: Record<string, string> = Object.create(null) as Record<string, string>;
	const sources: string[] = [];
	const broken: string[] = [];
	for (const path of [userConfigPath(), projectConfigPath(cwd)]) {
		let parsed: unknown;
		try {
			parsed = JSON.parse(stripBom(readFileSync(path, 'utf8')));
		} catch {
			if (existsSync(path)) broken.push(path);
			continue;
		}
		if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
			broken.push(path);
			continue;
		}
		for (const [key, value] of Object.entries(parsed as Config)) {
			config[key] = value;
			origin[key] = path;
		}
		sources.push(path);
	}
	return {config, sources, origin, broken};
}

// Read-modify-write: keep the other keys in the file (including the ones we do not know — those are the user's own)
export function writeConfigKey(path: string, key: string, value: unknown): void {
	let current: Record<string, unknown> = {};
	if (existsSync(path)) {
		let parsed: unknown;
		try {
			parsed = JSON.parse(stripBom(readFileSync(path, 'utf8')));
		} catch {
			// Overwriting a broken file would erase the user's existing keys: refuse instead and let them fix it first
			throw new Error(`${path} is not valid JSON; not writing`);
		}
		if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
			throw new Error(`${path} top level is not an object; not writing`);
		}
		current = parsed as Record<string, unknown>;
	}
	current[key] = value;
	mkdirSync(dirname(path), {recursive: true});
	// Write a temp file first, then rename atomically: writing the target directly could leave half a JSON behind on a crash,
	// which the next load would skip as a broken file — the user would see 'the config is gone' instead of 'the last write failed'
	const tmp = `${path}.${process.pid}.tmp`;
	try {
		writeFileSync(tmp, `${JSON.stringify(current, null, 2)}\n`, 'utf8');
		renameSync(tmp, path);
	} catch (error) {
		// A half-written tmp file left in the config dir is just garbage; failing to remove it must not hide the original error
		try {
			rmSync(tmp, {force: true});
		} catch {}
		throw error;
	}
}

// ── host version gate ───────────────────────────────────────────────────────────────
// The floor was measured, not guessed: fetched the dist/cli.mjs of two adjacent npm versions and compared them
// (1.9.0 / 1.10.0), then re-verified on 1.20 / 1.30 / 1.40 / 1.50 / 1.54.
// The latest dependency to appear is cmd.ui.capabilities — the mod relies on it to decide whether the host renders the footer at all.
// ModUi in 1.9.0 does not have this property yet (in that version capabilities only appears in the MCP protocol and prompt text),
// so cmd.ui.capabilities.status throws a TypeError outright: not a degradation, a crash. It exists from 1.10.0 on.
// Every other dependency (the modals, the subagent_stop / session_titled / config_setting_changed events,
// effort on model_request_end, the transcript tail shape, exec's signal, run_start's sessionId)
// already exists in 1.10.0; and ModUi's confirm/select/input/capabilities implementations (after normalising
// the minified identifier names) are identical in 1.10.0 and 1.54.0 — not merely present, their semantics do not drift with the version.
export const MIN_HOST_VERSION = '1.10.0';

// Host version: cmd's surface has no version field at all (probed: not among cmd's keys), so it can only be read from the
// package.json next to the CLI entry. When unreadable, return undefined — then no version check is done at all, avoiding false alarms.
export function hostVersion(): string | undefined {
	try {
		const entry = process.argv?.[1];
		if (!entry) return undefined;
		const manifest = JSON.parse(
			readFileSync(join(dirname(entry), '..', 'package.json'), 'utf8'),
		) as {name?: unknown; version?: unknown};
		// argv[1] is not necessarily cmdc (when running tests it is the test file itself): a name mismatch means no
		if (manifest.name !== 'command-code') return undefined;
		// Only accept version strings starting with a digit: '' and 'unknown' cannot be compared at all and must count as unreadable.
		// Otherwise they would parse as 0 and be compared against MIN_HOST_VERSION, declaring a perfectly good install stale and disabling it.
		if (typeof manifest.version !== 'string' || !/^\d/.test(manifest.version)) return undefined;
		return manifest.version;
	} catch {
		return undefined;
	}
}

export function versionAtLeast(actual: string, minimum: string): boolean {
	const parts = (text: string): number[] =>
		text.split('.').map(part => Number.parseInt(part, 10) || 0);
	const left = parts(actual);
	const right = parts(minimum);
	for (let index = 0; index < Math.max(left.length, right.length); index += 1) {
		const a = left[index] ?? 0;
		const b = right[index] ?? 0;
		if (a !== b) return a > b;
	}
	return true;
}

// ── session data (transcript / meta / user config) ──────────────────────────────────
function sessionPath(sessionId: string, cwd: string, suffix: string): string {
	const slug = cwd.replace(/^[/\\]+/, '').replace(/[/\\:]+/g, '-');
	return join(homedir(), '.commandcode', 'projects', slug, `${sessionId}${suffix}`);
}

function readSessionTitle(sessionId: string, cwd: string): string | undefined {
	try {
		const meta = JSON.parse(
			readFileSync(sessionPath(sessionId, cwd, '.meta.json'), 'utf8'),
		) as {title?: unknown};
		return typeof meta.title === 'string' && meta.title.trim() ? meta.title : undefined;
	} catch {
		return undefined;
	}
}

type SessionSeed = {
	readonly costUsd: number;
	readonly model?: string;
	readonly effort?: string;
	readonly usage?: Usage;
	/** the transcript has usage+model records but not a single tail anchor matched → the product's record format may have changed */
	readonly drifted?: boolean;
};

// Assistant message entries put usage / model / effort at the end of the line (content body first):
// {"type":"message",…,"message":{…},"usage":{…},"model":"…","effort":"…"}
// The tail anchoring is there so that lookalike text inside the message body cannot fool us.
const ASSISTANT_TAIL = /"usage":\{([^}]*)\},"model":"([^"]+)"(?:,"effort":"([^"]+)")?\}$/;

function usageFromFields(fields: string): Usage {
	const number = (key: string): number | undefined => {
		const match = new RegExp(`"${key}":(\\d+)`).exec(fields);
		return match ? Number(match[1]) : undefined;
	};
	return {
		inputTokens: number('inputTokens'),
		outputTokens: number('outputTokens'),
		cacheReadTokens: number('cacheReadTokens'),
		cacheWriteTokens: number('cacheWriteTokens'),
	};
}

// Session total cost + the last request's model/effort/usage: obtained in one streaming pass (used when resuming a session,
// so the footer is right from the start instead of waiting for the next request). Regex extraction only, no JSON.parse —
// a single transcript line can reach hundreds of KB.
export async function readSessionSeed(
	sessionId: string,
	cwd: string,
): Promise<SessionSeed | undefined> {
	let reader: ReturnType<typeof createInterface> | undefined;
	try {
		reader = createInterface({
			input: createReadStream(sessionPath(sessionId, cwd, '.jsonl'), {
				encoding: 'utf8',
			}),
			crlfDelay: Infinity,
		});
		let total = 0;
		let model: string | undefined;
		let effort: string | undefined;
		let usage: Usage | undefined;
		// Count instead of just taking 'the last one': lines carrying both usage and model exist in the transcript but
		// match no tail anchor → the line shape changed. Without this signal, format drift silently becomes 'cost reset / context gone'.
		let usageLines = 0;
		let tailHits = 0;
		for await (const line of reader) {
			if (line.includes('"costUsd"')) {
				for (const match of line.matchAll(/"costUsd":\s*([\d.eE+-]+)/g)) {
					const value = Number(match[1]);
					if (Number.isFinite(value)) total += value;
				}
			}
			if (line.includes('"usage"') && line.includes('"model"')) usageLines += 1;
			const tail = ASSISTANT_TAIL.exec(line);
			if (tail) {
				tailHits += 1;
				model = tail[2];
				effort = tail[3];
				usage = usageFromFields(tail[1]);
			}
		}
		return {costUsd: total, model, effort, usage, drifted: usageLines > 0 && tailHits === 0};
	} catch {
		return undefined;
	} finally {
		reader?.close();
	}
}

// cmdc records the 'current model + the reasoning effort per model' in ~/.commandcode/config.json:
//   {"model":"deepseek/deepseek-v4.1-flash","reasoningEffort":{"deepseek/deepseek-v4.1-flash":"high"}}
// Right after cmdc starts there is no request to ask, so the first two segments (model, effort) can only be drawn from it.
export function readUserConfig(): {model?: string; reasoningEffort: Record<string, string>} {
	// Also prototype-free: otherwise a single '__proto__' in config.json could conjure an effort out of nowhere
	const reasoningEffort: Record<string, string> = Object.create(null) as Record<string, string>;
	try {
		const parsed = JSON.parse(
			readFileSync(join(homedir(), '.commandcode', 'config.json'), 'utf8'),
		) as {model?: unknown; reasoningEffort?: unknown};
		if (parsed.reasoningEffort && typeof parsed.reasoningEffort === 'object') {
			for (const [key, value] of Object.entries(
				parsed.reasoningEffort as Record<string, unknown>,
			)) {
				if (typeof value === 'string') reasoningEffort[key] = value;
			}
		}
		return {...(typeof parsed.model === 'string' ? {model: parsed.model} : {}), reasoningEffort};
	} catch {
		return {reasoningEffort};
	}
}

// ── ui copy (lang key: en) ──────────────────────────────────────────────────────────
// Flag descriptions and the version-gate notice are produced at registration time, when getFlag does not exist yet — they only
// look at lang in the config file; everything else follows the effective lang live (write lang=en and the next report is English). The two
// entry points make different trade-offs: reports and modals call currentLang() every time, registration-time descriptions read the config file only — CLI --mod-option lang=en cannot reach
// a description text that has already been registered; that is a host limitation, not something workable around here.
const L10N = {
	en: {
		builtin: 'builtin',
		userScope: 'user',
		projectScope: 'project',
		cliFlag: (flag: string) => `CLI (--mod-option ${flag})`,
		presetSource: (name: string) => `preset ${name}`,
		on: 'On',
		off: 'Off',
		userLevel: 'User level',
		projectLevel: 'Project level',
		done: 'Done',
		doneDesc: 'finish',
		allProjects: 'all projects',
		thisProject: 'this project only',
		scopeTitle: (preset: string) => `Which file should config go to? (current preset: ${preset})`,
		editorTitle: (scope: string, changed: number) =>
			`Status line · writing ${scope} · ${changed} changed this run`,
		presetTitle: 'Pick a preset (a single key can still override it)',
		langTitle: 'Pick the ui language',
		numberTitle: (name: string, expect: string, max?: number) =>
			`${name} (${expect}${max === undefined ? '' : `, max ${max}`})`,
		boolTitle: (name: string, desc: string) => `${name}: ${desc}`,
		confirmTitle: (name: string, value: string) => `Write ${name} = ${value}?`,
		confirmBody: (path: string, name: string, current: string, source: string, value: string) =>
			`${path}\n${name}: current ${current} (${source}) → write ${value}`,
		writeFailed: (msg: string) => `Write failed: ${msg}`,
		shadowed: (name: string, effective: string, source: string, scope: string) =>
			`${name} still resolves to ${effective} (source: ${source}) — the value just written to ${scope} is overridden by higher precedence; the line won't change`,
		wrote: (path: string, changes: readonly string[]) =>
			`Wrote ${path}:\n${changes.map(change => `  ${change}`).join('\n')}`,
		noChanges: 'No changes.',
		needTui: `Interactive config needs the TUI interaction modal (cmd.ui.select / input / confirm, requires cmdc ≥ ${MIN_HOST_VERSION}).`,
		noModal: 'No interaction modal this run (expected headless) — nothing was written.',
		noModalShort: 'Interactive config needs the TUI (select returns undefined headless; nothing was written).',
		lineLabel: 'Status line',
		dataLabel: 'Data',
		colon: ': ',
		configHead: 'Config (key / default / effective / source):',
		filesLabel: 'Files',
		windowUnknown: ' (window unknown)',
		priceUnknown: ' (price unknown)',
		notRepo: 'not a repo',
		unknown: 'unknown',
		restored: (v: string) => ` (incl. restored ${v})`,
		subNote: (v: string) => ` (~${v}, not counted in cost above)`,
		requires: (v: string) => ` (requires ≥ ${v})`,
		rendering: 'rendering',
		headless: 'not rendered this run (headless)',
		activeTag: ' (active)',
		brokenTag: ' (unreadable)',
		noFilesNote: '(neither config file took effect — check the source column per row: builtin / preset / CLI)',
		brokenFile: (path: string) =>
			`${path} is unreadable (invalid JSON or top level is not an object) — ignored entirely; no key applied`,
		unknownKey: (key: string, source: string) => `unknown key "${key}" (${source}) — typo?`,
		badValue: (key: string, expect: string, actual: string, source: string) =>
			`"${key}" has an unusable value: expected ${expect}, got ${actual} (${source}) — ignored`,
		unknownPreset: (value: string, source: string, effective: string) =>
			`unknown preset ${value} (${source}) — valid: ${PRESET_NAMES.join(' / ')}; ${
				effective === 'full' ? 'treated as full' : `effective preset=${effective}`
			}`,
		unknownLang: (value: string, source: string, effective: string) =>
			`unknown lang ${value} (${source}) — valid: en; effective lang=${effective}`,
		seedDrift:
			'the transcript has usage/model records but none matched the expected tail shape — ' +
			'the internal format may have changed; restored cost/context may be off',
		tip: `Tip: /statusline config edits interactively (writes + repaints right away, no /reload); a CLI override reads --mod-option ${flagName('<key>')}=<value>`,
		oldHost: (min: string, current: string) =>
			`statusline requires cmdc ≥ ${min} (current ${current}): old hosts are not supported; disabled. Update cmdc (cmdc update) and reopen the session.`,
		slowGit: (durationS: string, intervalS: number, gapS: number) =>
			`git status took ${durationS}s in this repo (≥ refresh=${intervalS}s): ` +
			`polling slowed to every ${gapS}s. Set refresh=0 to stop polling entirely.`,
	},
} as const;

// Widen the string fields to string so the copy table stays assignable to this shape
type Strings = {readonly [K in keyof (typeof L10N)['en']]: (typeof L10N)['en'][K] extends string ? string : (typeof L10N)['en'][K]};

// ── mod factory ─────────────────────────────────────────────────────────────────────
export default function (cmd: ModApi): void {
	// Read the config file first (pure file IO, no registered flag needed): the language of the version notice and of the flag
	// descriptions depends only on lang in the file — both are produced at registration time, when getFlag is not available yet.
	let {config, sources: configSources, origin: configOrigin, broken: configBroken} = loadConfig(
		cmd.cwd,
	);
	const fileLang = langOf(config['lang']) ?? 'en';

	// Version gate: this mod does not support old hosts and does not degrade.
	// A readable version that is genuinely too old → notify to upgrade and disable immediately, not even registering flags or commands —
	// better to do nothing at all than to leave a footer that 'reacts but is wrong'.
	// When the version cannot be read, do not guess (nothing can be decided then; treat it as usable and show cmdc=unknown in the report).
	const host = hostVersion();
	if (host !== undefined && !versionAtLeast(host, MIN_HOST_VERSION)) {
		const message = L10N[fileLang].oldHost(MIN_HOST_VERSION, host);
		try {
			cmd.ui.notify(message, 'error');
		} catch {
			// The notice channel may not exist on an old host; fall back to the terminal so the notice does not vanish entirely
			console.error(message);
		}
		return;
	}

	for (const spec of FLAG_SPECS) {
		cmd.addFlag(flagName(spec.name), {
			type: spec.type,
			default: spec.default,
			// The description text can only look at lang from the config file right now: the flag is not registered yet, so CLI overrides are out of reach
			description: fileLang === 'en' ? spec.descriptionEn : spec.description,
		});
	}

	let session = freshSession();
	let requestStartedAt = 0;
	let timer: NodeJS.Timeout | undefined;
	// git's adaptive gate: when the read finished (not when it started) + the last measured duration + whether 'slow' was already reported
	let gitFinishedAt = 0;
	let gitDurationMs = 0;
	let gitSlowNotified = false;
	let gitReading = false;

	const presetName = (): string => {
		const cli = cmd.getFlag(flagName('preset'));
		const configured = config['preset'];
		// The command line counts as an explicit override only when it differs from the built-in default (the host erases =value from argv)
		const raw =
			typeof cli === 'string' && cli !== 'full'
				? cli
				: typeof configured === 'string'
					? configured
					: 'full';
		return raw.toLowerCase();
	};

	// The effective source is data, not a string: the copy is produced at render time under the current lang,
	// otherwise an English report would be mixed with Chinese 'CLI / preset x' text.
	// The CLI entry carries the key name: the source column must say which flag 'command line' actually means — the report and selector
	// use short keys while the command line needs the prefixed flag name; the two names must be matched up here.
	type FlagSource =
		| {kind: 'cli'; key: string}
		| {kind: 'file'; path?: string}
		| {kind: 'preset'; name: string}
		| {kind: 'default'};

	// The single value-resolution entry point: flag() / flagNumber() / the report table all go through it,
	// so 'the effective value written in the table' and 'the value actually used' can never drift.
	// Precedence: command line (when different from the built-in default) > config file > preset > built-in default.
	const resolveFlag = (name: string): {value: unknown; source: FlagSource} => {
		const spec = FLAG_BY_NAME.get(name);
		const base = spec?.default;
		const cli = cmd.getFlag(flagName(name));
		if (spec && typeof cli === typeof base && cli !== base) {
			return {value: canonical(spec, cli), source: {kind: 'cli', key: name}};
		}
		const configured = config[name];
		if (spec && configured !== undefined && acceptsValue(spec, configured)) {
			return {value: canonical(spec, configured), source: {kind: 'file', path: configOrigin[name]}};
		}
		const preset = presetValue(presetName(), name);
		// Do not report 'preset x' when the preset value equals the built-in default — that line carries no information (full is an alias of the built-in default)
		if (preset !== undefined && preset !== base) {
			return {value: preset, source: {kind: 'preset', name: presetName()}};
		}
		return {value: preset ?? base, source: {kind: 'default'}};
	};

	const currentLang = (): Lang => langOf(resolveFlag('lang').value) ?? 'en';
	const s = (): Strings => L10N[currentLang()];

	const sourceText = (source: FlagSource): string => {
		const t = s();
		switch (source.kind) {
			case 'cli':
				return t.cliFlag(flagName(source.key));
			case 'file':
				return source.path === undefined
					? t.builtin
					: source.path === userConfigPath()
						? t.userScope
						: t.projectScope;
			case 'preset':
				return t.presetSource(source.name);
			default:
				return t.builtin;
		}
	};

	// The description language also switches live with the effective lang (the text registered at load time cannot be changed, but the interactive list is drawn by us)
	const specDesc = (spec: FlagSpec): string =>
		currentLang() === 'en' ? spec.descriptionEn : spec.description;

	// No fallback parameter: the default comes from the registry alone; passing another one at a call site would only create a second source of truth
	const flag = (name: string): boolean => resolveFlag(name).value === true;

	// The ceiling comes from spec.max in the registry instead of being passed at each call site (two copies would drift eventually)
	const flagNumber = (name: string): number => {
		const spec = FLAG_BY_NAME.get(name);
		return spec ? clampedNumber(spec, resolveFlag(name).value) : 0;
	};

	const reloadConfig = (): void => {
		({config, sources: configSources, origin: configOrigin, broken: configBroken} = loadConfig(
			cmd.cwd,
		));
	};

	// Keys present in the JSON that we do not know (typos), keys with unusable values, and unrecognised preset / lang values — all of
	// them are named, otherwise a user who edited the config gets no feedback and will just assume the feature is broken
	const configWarnings = (): string[] => {
		const t = s();
		const warnings: string[] = [];
		for (const [key, path] of Object.entries(configOrigin)) {
			const spec = FLAG_BY_NAME.get(key);
			if (!spec) {
				warnings.push(t.unknownKey(key, sourceText({kind: 'file', path})));
				continue;
			}
			if (!acceptsValue(spec, config[key])) {
				warnings.push(
					t.badValue(
						key,
						describeExpectation(spec, currentLang()),
						JSON.stringify(config[key]),
						sourceText({kind: 'file', path}),
					),
				);
			}
		}
		// Case-insensitive, so the check must normalise first — otherwise {"preset":"Minimal"} would be misreported as an unknown preset
		const cliPreset = cmd.getFlag(flagName('preset'));
		const configured = config['preset'];
		const bogus =
			typeof cliPreset === 'string' && cliPreset !== 'full' && !isPresetName(cliPreset.toLowerCase())
				? {value: cliPreset, where: t.cliFlag(flagName('preset'))}
				: typeof configured === 'string' && !isPresetName(configured.toLowerCase())
					? {value: configured, where: sourceText({kind: 'file', path: configOrigin['preset']})}
					: undefined;
		if (bogus) {
			// The outcome must be stated per the preset that will actually take effect: when the command line overrides the config, claiming 'treated as full' would be false
			const effective = isPresetName(presetName()) ? presetName() : 'full';
			warnings.push(t.unknownPreset(JSON.stringify(bogus.value), bogus.where, effective));
		}
		// lang is like preset: a string that cannot be recognised (e.g. "fr") → named + English used in practice; non-strings are already caught by badValue above
		const cliLang = cmd.getFlag(flagName('lang'));
		const confLang = config['lang'];
		const bogusLang =
			typeof cliLang === 'string' && langOf(cliLang) === undefined
				? {value: cliLang, where: t.cliFlag(flagName('lang'))}
				: typeof confLang === 'string' && langOf(confLang) === undefined
					? {value: confLang, where: sourceText({kind: 'file', path: configOrigin['lang']})}
					: undefined;
		if (bogusLang) {
			// State the outcome per what actually takes effect, as with preset: when the command line lang=en overrides a bad value in the file,
			// reporting a fixed fallback instead of the effective language would be a lie
			warnings.push(t.unknownLang(JSON.stringify(bogusLang.value), bogusLang.where, currentLang()));
		}
		return warnings;
	};

	const barWidth = (): number => flagNumber('bar-width');

	const asciiOnly = (): boolean => flag('ascii') || process.env.TERM === 'dumb';

	const colorEnabled = (): boolean => !process.env.NO_COLOR && !asciiOnly();

	const colorMode = (): ColorMode => {
		if (asciiOnly()) return 'ascii';
		return /truecolor|24bit/i.test(process.env.COLORTERM ?? '') ? 'truecolor' : 'ansi256';
	};

	const segments = (): Segments => ({
		model: flag('model'),
		effort: flag('effort'),
		context: flag('context'),
		bar: flag('bar'),
		percent: flag('percent'),
		cache: flag('cache'),
		cost: flag('cost'),
		speed: flag('speed'),
		sub: flag('sub'),
		name: flag('name'),
		git: flag('git'),
		cwd: flag('cwd'),
	});

	const terminalWidth = (): number => {
		const columns = process.stdout.columns ?? 0;
		if (!Number.isFinite(columns) || columns <= 0) return 0;
		return Math.max(20, columns - 2);
	};

	const cwdName = (): string | undefined => cwdBasename(cmd.cwd);

	const seedTitle = (): void => {
		const snapshot = session.snapshot;
		if (!flag('name') || !session.id || snapshot.title) return;
		const title = readSessionTitle(session.id, cmd.cwd);
		if (title) snapshot.title = title;
	};

	// Display value = the history restored from the transcript + the part produced by this process (both counted once, never twice)
	const updateCost = (): void => {
		session.snapshot.costUsd = session.seededCost + session.sessionCost;
	};

	// Model / effort from the config: fill only the still-empty segments; once the first request returns there is no need to read the disk
	const seedFromConfig = (): void => {
		const snapshot = session.snapshot;
		if (snapshot.model && snapshot.effort) return;
		const {model, reasoningEffort} = readUserConfig();
		if (!snapshot.model && model) snapshot.model = model;
		if (!snapshot.effort && snapshot.model) snapshot.effort = reasoningEffort[snapshot.model];
	};

	// An event that carries a sessionId different from the current session → drop the whole event: after a session swap,
	// late events of the old session (in-flight request completion, titled, turn_end, ...) must not be written into the new session's state.
	// If either side does not know the id it cannot be decided, so let it through — better to paint once too often than to filter out real events.
	const forCurrentSession = (event: unknown): boolean => {
		const id = (event as {sessionId?: unknown}).sessionId;
		return typeof id !== 'string' || session.id === undefined || id === session.id;
	};

	// Resuming a session: the transcript records what actually happened, which beats the guesses read from the config
	const seedSession = async (): Promise<void> => {
		if (session.seeded || !session.id) return;
		session.seeded = true;
		const snapshot = session.snapshot;
		const seed = await readSessionSeed(session.id, cmd.cwd);
		// The session may have been swapped while awaiting: that transcript belongs to the old session, discard it whole
		if (!seed || session.snapshot !== snapshot) return;
		if (seed.drifted) session.seedDrifted = true;
		if (seed.costUsd > 0) session.seededCost = seed.costUsd;
		if (seed.model) snapshot.model = seed.model;
		if (seed.effort) snapshot.effort = seed.effort;
		if (seed.usage) {
			if (typeof seed.usage.inputTokens === 'number') {
				snapshot.contextTokens = seed.usage.inputTokens;
			}
			const hit = cacheHitRate(seed.usage);
			if (hit !== undefined) snapshot.cacheHit = hit;
		}
		updateCost();
		refresh();
	};

	// Three things can be restored at startup: model/effort from the config, the session name, and the history totals from the transcript.
	// Both entry points (onSessionStart and run_start) must run the same set — either can arrive first, and repeating is idempotent.
	const seedFromKnownSources = (): void => {
		seedFromConfig();
		seedTitle();
		void seedSession();
	};

	// Notify once when a single read takes longer than the configured refresh interval: that is exactly the invisible failure of 'users do not know their repo is slow'
	const noteSlowGit = (): void => {
		if (gitSlowNotified) return;
		const intervalMs = flagNumber('refresh') * 1000;
		if (intervalMs <= 0 || gitDurationMs < intervalMs) return;
		gitSlowNotified = true;
		cmd.ui.notify(
			s().slowGit(
				(gitDurationMs / 1000).toFixed(1),
				intervalMs / 1000,
				Math.round(gitGapMs(gitDurationMs) / 1000),
			),
			'warning',
		);
	};

	const readGit = async (): Promise<void> => {
		// Adaptive gate: a slow repo widens the interval by itself (the interval is measured from when the last read finished, not when it started —
		// otherwise an 8 second call returns after the 5 second TTL has long expired and every later event triggers another read)
		if (gitReading || Date.now() - gitFinishedAt < gitGapMs(gitDurationMs)) return;
		gitReading = true;
		const startedAt = Date.now();
		// Timeout backstop: a hung git (locks, dead mounts, huge repos) must not leave this read pending forever
		const controller = new AbortController();
		const killer = setTimeout(() => controller.abort(), GIT_TIMEOUT_MS);
		try {
			const {stdout, code} = await cmd.exec({
				command: 'git',
				args: ['status', '--porcelain=v1', '-b'],
				cwd: cmd.cwd,
				signal: controller.signal,
			});
			const info =
				code === 0
					? parseGitStatus(stdout)
					: {
							isRepo: false,
							ahead: 0,
							behind: 0,
							staged: 0,
							modified: 0,
							untracked: 0,
						};
			// git results are repo properties and do not change with the session: write them into the 'current' session (a swap while awaiting does not lose this read)
			const snapshot = session.snapshot;
			snapshot.isRepo = info.isRepo;
			snapshot.branch = info.branch;
			snapshot.ahead = info.ahead;
			snapshot.behind = info.behind;
			snapshot.staged = info.staged;
			snapshot.modified = info.modified;
			snapshot.untracked = info.untracked;
		} catch {
			session.snapshot.isRepo = false;
			session.snapshot.branch = undefined;
		} finally {
			clearTimeout(killer);
			gitReading = false;
			gitDurationMs = Date.now() - startedAt;
			gitFinishedAt = Date.now();
			noteSlowGit();
			// Paint again once git returns; in a slow repo that only makes the git segment appear a bit later, it does not hold up other segments
			paint();
		}
	};

	const composer = (): string =>
		composeLine(session.snapshot, segments(), {
			color: colorEnabled(),
			rawModel: flag('raw-model'),
			mode: colorMode(),
			barWidth: barWidth(),
			maxWidth: terminalWidth(),
			cwd: cwdName(),
		});

	// Whether this run renders the footer at all. Two things merge into one decision here:
	//   status === false  → the host explicitly says it does not paint (headless)
	//   capabilities missing → a 1.9.0 style old host, and the version gate is best-effort (it does not guess when the version is unreadable and lets it through),
	//                       so execution reaches here. Reading .status directly would turn every event into a mod_error,
	//                       and falling back to 'paint nothing' is more decent than erroring continuously in the user's session.
	// The report must tell these two cases apart, so it does not use this function and reads the three-state value directly.
	const rendersFooter = (): boolean => cmd.ui.capabilities?.status === true;

	// ---- cmdc-statusline-plus: account 5h / weekly windows ----
	// Reads the UNDOCUMENTED endpoint api.commandcode.ai/alpha/billing/credits using the CLI
	// key from ~/.commandcode/auth.json. Any failure clears the segment; never throws.
	const USAGE_ENDPOINT = 'https://api.commandcode.ai/alpha/billing/credits';
	const USAGE_POLL_MS = 120_000;
	type UsageWindow = {used?: number; cap?: number; resetAt?: number};
	let limitsData: {fiveHour?: UsageWindow; weekly?: UsageWindow} | null = null;
	let limitsTimer: ReturnType<typeof setInterval> | undefined;
	// Colour a value with the module palette (composeLine paints with its own local helper).
	const sgr = (code: string, text: string): string =>
		colorEnabled() ? `${code}${text}${ANSI.reset}` : text;
	const usageUntil = (resetAt?: number): string => {
		if (typeof resetAt !== 'number') return '';
		const ms = resetAt - Date.now();
		if (ms <= 0) return '';
		const m = Math.floor(ms / 60000);
		const d = Math.floor(m / 1440);
		const h = Math.floor((m % 1440) / 60);
		if (d > 0) return `↻${d}d${h}h`;
		if (h > 0) return `↻${h}h${m % 60}m`;
		return `↻${m}m`;
	};
	// Same visual language as the built-in segments: the shared gradient bar, dim separators,
	// and the context colour rule (>=90 red, >=80 yellow, else gray).
	const usageText = (): string => {
		const data = limitsData;
		if (!data) return '';
		const segment = (label: string, win?: UsageWindow): string => {
			if (!win || typeof win.used !== 'number' || typeof win.cap !== 'number' || win.cap <= 0) return '';
			const percent = (win.used / win.cap) * 100;
			const code = percent >= 90 ? ANSI.red : percent >= 80 ? ANSI.yellow : ANSI.gray;
			const bar = renderBar(percent, barWidth(), colorMode(), colorEnabled());
			const reset = usageUntil(win.resetAt);
			return [sgr(ANSI.gray, label), bar, sgr(code, `${Math.round(percent)}%`), reset ? sgr(ANSI.dim, reset) : '']
				.filter(Boolean)
				.join(' ');
		};
		return [segment('5h', data.fiveHour), segment('week', data.weekly)]
			.filter(Boolean)
			.join(sgr(ANSI.dim, SEP));
	};
	const readUsage = async (): Promise<{fiveHour?: UsageWindow; weekly?: UsageWindow} | null> => {
		try {
			const raw = readFileSync(join(homedir(), '.commandcode', 'auth.json'), 'utf8');
			const key = (JSON.parse(raw) as {apiKey?: unknown}).apiKey;
			if (typeof key !== 'string' || key.length === 0) return null;
			const res = await fetch(USAGE_ENDPOINT, {headers: {Authorization: `Bearer ${key}`}});
			if (!res.ok) return null;
			const data = (await res.json()) as {windowLimits?: {fiveHour?: UsageWindow; weekly?: UsageWindow}};
			return data.windowLimits ?? null;
		} catch {
			return null;
		}
	};
	const refreshLimits = async (): Promise<void> => {
		limitsData = await readUsage();
		paint();
	};
	const startLimitsTimer = (): void => {
		void refreshLimits();
		if (!limitsTimer) {
			limitsTimer = setInterval(() => {
				void refreshLimits();
			}, USAGE_POLL_MS);
			limitsTimer.unref?.();
		}
	};
	const stopLimitsTimer = (): void => {
		if (limitsTimer) {
			clearInterval(limitsTimer);
			limitsTimer = undefined;
		}
		limitsData = null;
	};

	// Repainting is synchronous and idempotent (the host dedupes identical text itself), so it never waits for git:
	// refresh() used to await git before painting, so an 8 second git status stalled model/cost/context for 8 seconds as well.
	const paint = (): void => {
		if (!rendersFooter()) return;
		const line = [sgr(ANSI.magenta, BRAND), composer(), usageText()]
			.filter(Boolean)
			.join(sgr(ANSI.dim, SEP));
		cmd.ui.setStatus(line || null);
	};

	const refresh = (): void => {
		// If this run does not render the footer (headless), do nothing at all: not even a git process should start
		if (!rendersFooter()) return;
		paint();
		// Whether git is actually read is decided by readGit's adaptive gate; this only sends the request out
		if (flag('git')) void readGit();
	};

	const startTimer = (): void => {
		const seconds = flagNumber('refresh');
		if (seconds <= 0 || timer) return;
		// The timer's only job is 'external changes': in-process events refresh anyway.
		// It no longer pokes a timestamp to force a read — whether one is allowed is decided solely by the gate computed from the measured duration.
		timer = setInterval(() => refresh(), seconds * 1000);
		timer.unref?.();
	};

	const stopTimer = (): void => {
		if (!timer) return;
		clearInterval(timer);
		timer = undefined;
	};

	const onResize = (): void => {
		refresh();
	};

	cmd.hooks({
		onSessionStart: info => {
			const data = info as unknown as SessionEvent;
			const id = typeof data.sessionId === 'string' ? data.sessionId : undefined;
			// The host swaps sessions in the same process (onSessionEnd's reason can be 'replaced'): when the id changes, rebuild everything,
			// otherwise the previous session's name/cost/seed flags leak straight into the new session. Re-firing with the same id must not reset —
			// that would zero the running session's totals.
			if (id !== undefined && id !== session.id) {
				session = freshSession(id);
				requestStartedAt = 0;
			}
			seedFromKnownSources();
			startTimer();
			startLimitsTimer();
			// Idempotent: if start fires again after a session swap, avoid stacking listeners
			process.stdout.off('resize', onResize);
			process.stdout.on('resize', onResize);
			// The first git read of a new session is always worth it (a session swap must not be blocked by the previous session's backoff gate)
			gitFinishedAt = 0;
			refresh();
		},
		onSessionEnd: () => {
			stopTimer();
			stopLimitsTimer();
			process.stdout.off('resize', onResize);
			cmd.ui.setStatus(null);
		},
	});

	cmd.on('run_start', event => {
		const data = event as unknown as SessionEvent;
		if (!forCurrentSession(event)) return;
		// Adopt an id only when there is none yet: a run's sessionId should belong to the current session,
		// and resetting on a different id would wipe the whole session state for one unexpected nested run
		if (session.id === undefined && typeof data.sessionId === 'string') session.id = data.sessionId;
		seedFromKnownSources();
		refresh();
	});

	cmd.on('session_titled', event => {
		if (!forCurrentSession(event)) return;
		const data = event as unknown as {title?: unknown};
		if (typeof data.title === 'string' && data.title.trim()) {
			session.snapshot.title = data.title;
		}
		refresh();
	});

	cmd.on('model_request_start', event => {
		if (!forCurrentSession(event)) return;
		const data = event as unknown as ModelEvent;
		if (typeof data.model === 'string') session.snapshot.model = data.model;
		requestStartedAt = Date.now();
		refresh();
	});

	cmd.on('model_request_end', event => {
		if (!forCurrentSession(event)) return;
		const data = event as unknown as ModelEvent;
		const snapshot = session.snapshot;
		if (typeof data.model === 'string') snapshot.model = data.model;
		if (typeof data.effort === 'string') snapshot.effort = data.effort;
		if (typeof data.usage?.inputTokens === 'number') {
			snapshot.contextTokens = data.usage.inputTokens;
		}
		if (data.usage) {
			const hit = cacheHitRate(data.usage);
			if (hit !== undefined) snapshot.cacheHit = hit;
			const cost = estimateCost(data.usage, snapshot.model);
			if (cost > 0) {
				session.sessionCost += cost;
				updateCost();
			}
			const output = data.usage.outputTokens ?? 0;
			const elapsed = (Date.now() - requestStartedAt) / 1000;
			if (requestStartedAt > 0 && elapsed > 0 && output > 0) {
				snapshot.speed = output / elapsed;
			}
		}
		refresh();
	});

	// Sub-agent model requests do not go through model_request_* (measured), so their usage can only be folded in from subagent_stop;
	// the product does not count sub-agent tokens in the transcript either, so only tokens are accumulated here, not exact cost.
	cmd.on('subagent_stop', event => {
		if (!forCurrentSession(event)) return;
		const data = event as unknown as SubagentStopEvent;
		if (typeof data.tokensUsed === 'number' && data.tokensUsed > 0) {
			session.snapshot.subTokens += data.tokensUsed;
			refresh();
		}
	});

	cmd.on('turn_end', event => {
		if (!forCurrentSession(event)) return;
		refresh();
	});

	cmd.on('config_setting_changed', event => {
		if (!forCurrentSession(event)) return;
		const data = event as unknown as ConfigChangedEvent;
		if (data.setting === 'model' && typeof data.value === 'string') {
			session.snapshot.model = data.value;
			// effort is stored per model, so a model change must change the value too — clear it when the config has none; keeping the previous model's effort would be wrong
			session.snapshot.effort = readUserConfig().reasoningEffort[data.value];
		}
		// Repaint right after /effort changes instead of waiting for the next model_request_end
		if (data.setting === 'effort' && typeof data.value === 'string') {
			session.snapshot.effort = data.value;
		}
		refresh();
	});

	// Display value of a key: numeric keys show the clamped value. Showing the raw config value would be wrong —
	// with bar-width: 100 the footer uses 40 (spec.max), so reporting 100 in the table would be a lie.
	const displayValue = (spec: FlagSpec, value: unknown): string => {
		if (spec.numeric) return String(clampedNumber(spec, value));
		if (typeof value === 'boolean') return value ? 'true' : 'false';
		return String(value ?? '-');
	};

	const presetHint = (name: string): string =>
		Object.entries(PRESETS[name] ?? {})
			.filter(([, on]) => on)
			.map(([key]) => key)
			.join(' + ');

	// Diagnostics: a 'key / default / effective / source' table + warnings.
	// It solves both 'the key names have no entry point' (no README digging) and 'changed it, no effect, no feedback' (unknown keys / bad values are named).
	const statuslineReport = (): string => {
		const t = s();
		const snapshot = session.snapshot;
		const plain = composeLine(snapshot, segments(), {
			color: false,
			rawModel: true,
			mode: 'ascii',
			barWidth: barWidth(),
			maxWidth: 0,
			cwd: cwdName(),
		});
		const window = contextWindowFor(snapshot.model);
		const priced = modelPriceFor(snapshot.model) !== undefined;
		const subEstimate =
			snapshot.subTokens > 0 && snapshot.costUsd > 0 && snapshot.contextTokens
				? (snapshot.costUsd / snapshot.contextTokens) * snapshot.subTokens
				: 0;
		const state = [
			`model=${snapshot.model ?? '-'}`,
			`effort=${snapshot.effort ?? '-'}`,
			`ctx=${snapshot.contextTokens ? formatTokens(snapshot.contextTokens) : '-'}${
				window ? `/${formatWindow(window)}` : t.windowUnknown
			}`,
			`cache=${snapshot.cacheHit !== undefined ? formatRate(snapshot.cacheHit) : '-'}`,
			`cost=${snapshot.costUsd > 0 ? formatCost(snapshot.costUsd) : '-'}${
				session.seededCost > 0 ? t.restored(formatCost(session.seededCost)) : ''
			}${priced ? '' : t.priceUnknown}`,
			`speed=${snapshot.speed ? `${Math.round(snapshot.speed)} tok/s` : '-'}`,
			`sub=${snapshot.subTokens > 0 ? `${formatTokens(snapshot.subTokens)}${t.subNote(formatCost(subEstimate))}` : '-'}`,
			`name=${snapshot.title ?? '-'}`,
			`git=${snapshot.isRepo ? (snapshot.branch ?? '-') : t.notRepo}`,
			`render=${asciiOnly() ? 'ascii' : colorMode()}`,
			`width=${terminalWidth() || t.unknown}`,
			`cmdc=${host ?? t.unknown}${t.requires(MIN_HOST_VERSION)}`,
			// Three states instead of two: the host saying 'not rendering' (headless) and the host lacking the property altogether (an old host whose
			// version was unreadable so the gate let it through) are different things; reporting the latter as headless would be a lie
			`footer=${
				cmd.ui.capabilities
					? cmd.ui.capabilities.status
						? t.rendering
						: t.headless
					: t.unknown
			}`,
		].join(' | ');

		const pad = (text: string, width: number): string => text.padEnd(width, ' ');
		const rows = FLAG_SPECS.map(spec => {
			const {value, source} = resolveFlag(spec.name);
			return [spec.name, String(spec.default), displayValue(spec, value), sourceText(source)];
		});
		// Column widths are computed from the content: hard-coded widths glue a column to the next one when a value grows (preset=minimal is exactly 7 characters)
		const columnWidth = (index: number): number =>
			Math.max(...rows.map(row => row[index].length)) + 1;
		const table = rows.map(row =>
			row.map((cell, index) => pad(cell, columnWidth(index))).join('').trimEnd(),
		);
		// Name both candidate files and mark whether this one could actually be read — listing only the 'loaded' ones would render
		// 'file exists but is broken' as 'there is no config file', which is exactly the case users most need to know about
		const files = [userConfigPath(), projectConfigPath(cmd.cwd)]
			.map(path =>
				configSources.includes(path)
					? `${path}${t.activeTag}`
					: configBroken.includes(path)
						? `${path}${t.brokenTag}`
						: path,
			)
			.join(' + ');

		const lines = [
			`${t.lineLabel}${t.colon}${plain}`,
			`${t.dataLabel}${t.colon}${state}`,
			t.configHead,
			...table,
			`${t.filesLabel}${t.colon}${files}`,
		];
		if (configSources.length === 0) {
			// Do not write 'everything falls back to the built-in default': without a config file the command line and presets can still set values,
			// and saying so would contradict the 'preset x / CLI' rows in the table above
			lines.push(t.noFilesNote);
		}
		for (const path of configBroken) {
			lines.push(`⚠ ${t.brokenFile(path)}`);
		}
		if (session.seedDrifted) {
			lines.push(`⚠ ${t.seedDrift}`);
		}
		for (const warning of configWarnings()) lines.push(`⚠ ${warning}`);
		lines.push(t.tip);
		return lines.join('\n');
	};

	// Interactive config: goes through cmd.ui.select/input/confirm (real modals in the TUI).
	// Under headless, select returns undefined, so the whole flow naturally falls back to 'print the diagnostics' and never writes files blindly.
	const configureStatusline = async (ui: ModApi['ui']): Promise<string> => {
		// The interaction modal may not exist (headless returns undefined; unusual hosts may lack these methods entirely,
		// or even ui itself): when one is missing, do not throw and become a mod_error, just fall back to printing the diagnostics
		const canAsk =
			typeof ui?.select === 'function' &&
			typeof ui?.input === 'function' &&
			typeof ui?.confirm === 'function';
		if (!canAsk) {
			return [s().needTui, s().noModal, '', statuslineReport()].join('\n');
		}
		// The scope keeps a semantic key, not a label: if the user changes lang mid-flow, the old label string no longer matches
		const scopePick = await ui.select({
			title: s().scopeTitle(presetName()),
			options: [
				{label: s().userLevel, description: `${userConfigPath()} · ${s().allProjects}`},
				{label: s().projectLevel, description: `${projectConfigPath(cmd.cwd)} · ${s().thisProject}`},
			],
		});
		if (scopePick === undefined) {
			return [s().noModalShort, '', statuslineReport()].join('\n');
		}
		const scopeKey = scopePick === s().userLevel ? 'user' : 'project';
		const path = scopeKey === 'user' ? userConfigPath() : projectConfigPath(cmd.cwd);
		const scopeLabel = () => (scopeKey === 'user' ? s().userLevel : s().projectLevel);
		const changes: string[] = [];
		const notes: string[] = [];

		for (;;) {
			const t = s();
			const pick = await ui.select({
				title: t.editorTitle(scopeLabel(), changes.length),
				options: [
					...FLAG_SPECS.map(spec => {
						const {value} = resolveFlag(spec.name);
						const shown = spec.numeric
							? String(clampedNumber(spec, value))
							: typeof value === 'boolean'
								? value
									? t.on
									: t.off
								: String(value);
						return {label: spec.name, description: `${shown} · ${specDesc(spec)}`};
					}),
					{label: t.done, description: t.doneDesc},
				],
			});
			if (pick === undefined || pick === t.done) break;
			const spec = FLAG_BY_NAME.get(pick);
			if (!spec) continue;

			let value: unknown;
			if (spec.name === 'preset') {
				value = await ui.select({
					title: t.presetTitle,
					options: PRESET_NAMES.map(name => ({label: name, description: presetHint(name)})),
				});
			} else if (spec.name === 'lang') {
				// lang is a string key but not free input: writing anything else only earns the 'unknown language' warning
				value = await ui.select({
					title: t.langTitle,
					options: [
						{label: 'en', description: 'English'},
					],
				});
			} else if (spec.numeric) {
				const typed = await ui.input({
					title: t.numberTitle(spec.name, describeExpectation(spec, currentLang()), spec.max),
					placeholder: String(spec.default),
				});
				const parsed = Number(typed);
				if (typed !== undefined && Number.isFinite(parsed)) value = parsed;
			} else {
				const picked = await ui.select({
					title: t.boolTitle(spec.name, specDesc(spec)),
					options: [
						{label: t.on, description: 'true'},
						{label: t.off, description: 'false'},
					],
				});
				if (picked !== undefined) value = picked === t.on;
			}
			if (value === undefined) continue;

			// Show 'what is actually in effect' rather than 'what this file says': a key of the same name may be overridden by another file,
			// and looking only at this file would make the user think the change is redundant (or, conversely, that it will take effect)
			const effective = resolveFlag(spec.name);
			const agreed = await ui.confirm({
				title: s().confirmTitle(spec.name, JSON.stringify(value)),
				message: s().confirmBody(
					path,
					spec.name,
					displayValue(spec, effective.value),
					sourceText(effective.source),
					JSON.stringify(value),
				),
			});
			if (!agreed) continue;

			try {
				writeConfigKey(path, spec.name, value);
			} catch (error) {
				ui.notify(s().writeFailed(error instanceof Error ? error.message : String(error)), 'error');
				continue;
			}
			changes.push(`${spec.name}=${JSON.stringify(value)}`);
			reloadConfig();
			// refresh changes the timer interval: restart it, otherwise 'no /reload needed' would be a lie
			stopTimer();
			startTimer();
			refresh();
			// Written to user scope while project scope has a key of the same name (or the command line overrides it) → the footer will not change.
			// This must be said to the user's face, otherwise they see 'written' with no visible change and assume the feature is broken
			const applied = resolveFlag(spec.name);
			if (displayValue(spec, applied.value) !== displayValue(spec, value)) {
				notes.push(
					s().shadowed(
						spec.name,
						displayValue(spec, applied.value),
						sourceText(applied.source),
						scopeLabel(),
					),
				);
			}
		}

		const head =
			changes.length > 0 ? s().wrote(path, changes) : s().noChanges;
		return [head, ...notes.map(note => `⚠ ${note}`), '', statuslineReport()].join('\n');
	};

	cmd.addCommand({
		name: 'statusline',
		description: 'inspect the status line and config sources; `/statusline config` edits interactively',
		handler: async (context: {args?: unknown; ui?: ModApi['ui']}) => {
			const sub = String(context?.args ?? '').trim().toLowerCase();
			if (sub === 'config') {
				return {message: await configureStatusline(context?.ui ?? cmd.ui)};
			}
			return {message: statuslineReport()};
		},
	});
}

// ── generated section (machine-written, do not edit by hand) ────────────────────────
// scripts/gen-model-tables.py generates both tables from the model list bundled with the CLI; CI compares them with --check to catch drift.
// They sit at the end of the file so the hand-written code above stays contiguous — they are an appendix, off the reading path;
// everything above uses the tables only through contextWindowFor / modelPriceFor, so the tables need not sit next to their call sites.
// >>> GENERATED:WINDOWS (generated by scripts/gen-model-tables.py, do not edit by hand)
// Context window table: models whose window the manifest does not publish (zai-org/GLM-5.1, MiniMaxAI/MiniMax-M2.7, Qwen/Qwen3.6-Max-Preview, Qwen/Qwen3.6-Plus) are absent,
// so a miss shows the token count only, without percentage or bar (same for BYOK / custom endpoint models).
const MODEL_CONTEXT_WINDOWS: Record<string, number> = {
	'MiniMaxAI/MiniMax-M2.5': 200000,
	'MiniMaxAI/MiniMax-M3': 1000000,
	'Qwen/Qwen3.7-Flash': 1000000,
	'Qwen/Qwen3.7-Max': 1000000,
	'Qwen/Qwen3.7-Plus': 1000000,
	'Qwen/Qwen3.8-27B': 262000,
	'Qwen/Qwen3.8-Flash': 1000000,
	'Qwen/Qwen3.8-Max': 1000000,
	'Qwen/Qwen3.8-Max-0902': 1000000,
	'claude-fable-5': 1000000,
	'claude-fable-5-1': 1000000,
	'claude-haiku-4-5-20251001': 200000,
	'claude-opus-4-7': 1000000,
	'claude-opus-4-8': 1000000,
	'claude-opus-5': 1000000,
	'claude-sonnet-4-6': 1000000,
	'claude-sonnet-5': 1000000,
	'deepseek/deepseek-v4-flash': 1000000,
	'deepseek/deepseek-v4-flash-fast': 1000000,
	'deepseek/deepseek-v4-flash-vision-exp': 1000000,
	'deepseek/deepseek-v4-pro': 1000000,
	'deepseek/deepseek-v4.1-flash': 1000000,
	'google/gemini-3.1-flash-lite': 1000000,
	'google/gemini-3.5-flash': 1000000,
	'google/gemini-3.5-flash-lite': 1000000,
	'google/gemini-3.6-flash': 1000000,
	'google/gemini-3.7-flash': 1050000,
	'google/gemini-3.8-flash': 1000000,
	'gpt-5.3-codex': 400000,
	'gpt-5.4': 400000,
	'gpt-5.4-mini': 400000,
	'gpt-5.5': 400000,
	'gpt-5.6-luna': 1050000,
	'gpt-5.6-sol': 1050000,
	'gpt-5.6-terra': 1050000,
	'gpt-6-astra': 1050000,
	'inclusionai/ling-3.0-flash-sante:free': 262000,
	'meituan/LongCat-2.0:free': 1050000,
	'meta/muse-spark-1.1': 1050000,
	'meta/muse-spark-1.2': 1050000,
	'meta/muse-spark-1.2-contributor': 1050000,
	'meta/muse-spark-1.3': 1050000,
	'meta/muse-spark-1.3-contributor': 1050000,
	'moonshotai/Kimi-K2.5': 256000,
	'moonshotai/Kimi-K2.6': 256000,
	'moonshotai/Kimi-K2.7-Code': 256000,
	'moonshotai/Kimi-K2.7-Code-Highspeed': 262000,
	'moonshotai/Kimi-K3': 1000000,
	'nvidia/nemotron-3-ultra-550b-a55b': 1000000,
	'poolside/laguna-s-2.1-free': 256000,
	'sakana/fugu-ultra': 1000000,
	'stepfun/Step-3.5-Flash': 1000000,
	'stepfun/Step-3.7-Flash': 256000,
	'tencent/hy3-paid': 262000,
	'tencent/hy4-preview': 1050000,
	'thinkingmachines/inkling': 256000,
	'thinkingmachines/inkling-small': 1000000,
	'xai/grok-4.5': 500000,
	'xai/grok-4.6': 500000,
	'xiaomi/mimo-v2.5': 1000000,
	'xiaomi/mimo-v2.5-pro': 1000000,
	'z-ai/glm-5.3-flash': 1050000,
	'zai-org/GLM-5': 200000,
	'zai-org/GLM-5.2': 1000000,
	'zai-org/GLM-5.2-Fast': 1000000,
	'zai-org/GLM-5.3': 1000000,
};
// <<< GENERATED:WINDOWS

// >>> GENERATED:PRICES (generated by scripts/gen-model-tables.py, do not edit by hand)
// Price table (USD / 1M tokens, including cache read and write prices): cost is accumulated from usage; the formula has been checked line by line against the product's recorded costUsd
type ModelPrice = {
	readonly in: number;
	readonly out: number;
	readonly cacheRead: number;
	readonly cacheWrite: number;
};

const MODEL_PRICES: Record<string, ModelPrice> = {
	'MiniMaxAI/MiniMax-M2.5': {in: 0.3, out: 1.2, cacheRead: 0.03, cacheWrite: 0},
	'MiniMaxAI/MiniMax-M2.7': {in: 0.3, out: 1.2, cacheRead: 0.06, cacheWrite: 0},
	'MiniMaxAI/MiniMax-M3': {in: 0.3, out: 1.2, cacheRead: 0.06, cacheWrite: 0},
	'Qwen/Qwen3.6-Max-Preview': {in: 1.3, out: 7.8, cacheRead: 0.26, cacheWrite: 1.63},
	'Qwen/Qwen3.6-Plus': {in: 0.5, out: 3, cacheRead: 0.1, cacheWrite: 0},
	'Qwen/Qwen3.7-Flash': {in: 0.03, out: 0.13, cacheRead: 0.006, cacheWrite: 0.038},
	'Qwen/Qwen3.7-Max': {in: 2.5, out: 7.5, cacheRead: 0.5, cacheWrite: 3.13},
	'Qwen/Qwen3.7-Plus': {in: 0.4, out: 1.6, cacheRead: 0.08, cacheWrite: 0.5},
	'Qwen/Qwen3.8-27B': {in: 0.4, out: 3, cacheRead: 0.04, cacheWrite: 0},
	'Qwen/Qwen3.8-Flash': {in: 0.16, out: 0.47, cacheRead: 0.016, cacheWrite: 0},
	'Qwen/Qwen3.8-Max': {in: 2, out: 6, cacheRead: 0.25, cacheWrite: 2.5},
	'Qwen/Qwen3.8-Max-0902': {in: 2, out: 6, cacheRead: 0.25, cacheWrite: 0},
	'claude-fable-5': {in: 10, out: 50, cacheRead: 1, cacheWrite: 12.5},
	'claude-fable-5-1': {in: 10, out: 50, cacheRead: 0.25, cacheWrite: 12.5},
	'claude-haiku-4-5-20251001': {in: 1, out: 5, cacheRead: 0.1, cacheWrite: 1.25},
	'claude-opus-4-7': {in: 5, out: 25, cacheRead: 0.5, cacheWrite: 6.25},
	'claude-opus-4-8': {in: 5, out: 25, cacheRead: 0.5, cacheWrite: 6.25},
	'claude-opus-5': {in: 5, out: 25, cacheRead: 0.5, cacheWrite: 6.25},
	'claude-sonnet-4-6': {in: 3, out: 15, cacheRead: 0.3, cacheWrite: 3.75},
	'claude-sonnet-5': {in: 2, out: 10, cacheRead: 0.2, cacheWrite: 2.5},
	'deepseek/deepseek-v4-flash': {in: 0.15, out: 0.6, cacheRead: 0.003, cacheWrite: 0},
	'deepseek/deepseek-v4-flash-fast': {in: 0.28, out: 0.56, cacheRead: 0.07, cacheWrite: 0},
	'deepseek/deepseek-v4-flash-vision-exp': {in: 0.15, out: 0.6, cacheRead: 0.003, cacheWrite: 0},
	'deepseek/deepseek-v4-pro': {in: 0.66, out: 1.98, cacheRead: 0.022, cacheWrite: 0},
	'deepseek/deepseek-v4.1-flash': {in: 0.15, out: 0.6, cacheRead: 0.003, cacheWrite: 0},
	'google/gemini-3.1-flash-lite': {in: 0.25, out: 1.5, cacheRead: 0.03, cacheWrite: 0},
	'google/gemini-3.5-flash': {in: 1.5, out: 9, cacheRead: 0.15, cacheWrite: 0},
	'google/gemini-3.5-flash-lite': {in: 0.3, out: 2.5, cacheRead: 0.03, cacheWrite: 0},
	'google/gemini-3.6-flash': {in: 1.5, out: 7.5, cacheRead: 0.15, cacheWrite: 0},
	'google/gemini-3.7-flash': {in: 1.5, out: 7.5, cacheRead: 0.15, cacheWrite: 0.08334},
	'google/gemini-3.8-flash': {in: 1.5, out: 7.5, cacheRead: 0.15, cacheWrite: 0},
	'gpt-5.3-codex': {in: 2, out: 8, cacheRead: 0.5, cacheWrite: 0},
	'gpt-5.4': {in: 2.5, out: 15, cacheRead: 0.25, cacheWrite: 0},
	'gpt-5.4-mini': {in: 0.75, out: 4.5, cacheRead: 0.075, cacheWrite: 0},
	'gpt-5.5': {in: 5, out: 30, cacheRead: 0.5, cacheWrite: 0},
	'gpt-5.6-luna': {in: 0.2, out: 1.2, cacheRead: 0.02, cacheWrite: 0.25},
	'gpt-5.6-sol': {in: 5, out: 30, cacheRead: 0.5, cacheWrite: 6.25},
	'gpt-5.6-terra': {in: 2, out: 12, cacheRead: 0.2, cacheWrite: 2.5},
	'gpt-6-astra': {in: 10, out: 50, cacheRead: 1, cacheWrite: 12.5},
	'inclusionai/ling-3.0-flash-sante:free': {in: 0, out: 0, cacheRead: 0, cacheWrite: 0},
	'meituan/LongCat-2.0:free': {in: 0, out: 0, cacheRead: 0, cacheWrite: 0},
	'meta/muse-spark-1.1': {in: 1.25, out: 4.25, cacheRead: 0.15, cacheWrite: 0},
	'meta/muse-spark-1.2': {in: 1.25, out: 4.25, cacheRead: 0.15, cacheWrite: 0},
	'meta/muse-spark-1.2-contributor': {in: 0.1, out: 0.2, cacheRead: 0.002, cacheWrite: 0},
	'meta/muse-spark-1.3': {in: 1.25, out: 4.25, cacheRead: 0.15, cacheWrite: 0},
	'meta/muse-spark-1.3-contributor': {in: 0.1, out: 0.2, cacheRead: 0.002, cacheWrite: 0},
	'moonshotai/Kimi-K2.5': {in: 0.6, out: 3, cacheRead: 0.1, cacheWrite: 0},
	'moonshotai/Kimi-K2.6': {in: 0.95, out: 4, cacheRead: 0.16, cacheWrite: 0},
	'moonshotai/Kimi-K2.7-Code': {in: 0.95, out: 4, cacheRead: 0.19, cacheWrite: 0},
	'moonshotai/Kimi-K2.7-Code-Highspeed': {in: 1.9, out: 8, cacheRead: 0.38, cacheWrite: 0},
	'moonshotai/Kimi-K3': {in: 3, out: 15, cacheRead: 0.3, cacheWrite: 0},
	'nvidia/nemotron-3-ultra-550b-a55b': {in: 0.6, out: 2.4, cacheRead: 0.12, cacheWrite: 0},
	'poolside/laguna-s-2.1-free': {in: 0, out: 0, cacheRead: 0, cacheWrite: 0},
	'sakana/fugu-ultra': {in: 5, out: 30, cacheRead: 0.5, cacheWrite: 0},
	'stepfun/Step-3.5-Flash': {in: 0.1, out: 0.3, cacheRead: 0.02, cacheWrite: 0},
	'stepfun/Step-3.7-Flash': {in: 0.2, out: 1.15, cacheRead: 0.04, cacheWrite: 0},
	'tencent/hy3-paid': {in: 0.14, out: 0.58, cacheRead: 0.035, cacheWrite: 0},
	'tencent/hy4-preview': {in: 0.834, out: 2.501, cacheRead: 0.042, cacheWrite: 0},
	'thinkingmachines/inkling': {in: 1, out: 4.05, cacheRead: 0.17, cacheWrite: 0},
	'thinkingmachines/inkling-small': {in: 0.5, out: 1.2, cacheRead: 0.1, cacheWrite: 0},
	'xai/grok-4.5': {in: 2, out: 6, cacheRead: 0.5, cacheWrite: 0},
	'xai/grok-4.6': {in: 2, out: 6, cacheRead: 0.5, cacheWrite: 0},
	'xiaomi/mimo-v2.5': {in: 0.14, out: 0.28, cacheRead: 0.0028, cacheWrite: 0},
	'xiaomi/mimo-v2.5-pro': {in: 0.435, out: 0.87, cacheRead: 0.0036, cacheWrite: 0},
	'z-ai/glm-5.3-flash': {in: 0.15, out: 0.5, cacheRead: 0.03, cacheWrite: 0},
	'zai-org/GLM-5': {in: 1, out: 3.2, cacheRead: 0.2, cacheWrite: 0},
	'zai-org/GLM-5.1': {in: 1.4, out: 4.4, cacheRead: 0.26, cacheWrite: 0},
	'zai-org/GLM-5.2': {in: 1.4, out: 4.4, cacheRead: 0.26, cacheWrite: 0},
	'zai-org/GLM-5.2-Fast': {in: 3, out: 10.25, cacheRead: 0.5, cacheWrite: 0},
	'zai-org/GLM-5.3': {in: 1.4, out: 4.4, cacheRead: 0.26, cacheWrite: 0},
};
// <<< GENERATED:PRICES
